package org.firstinspires.ftc.teamcode.util;

public enum GamepadButtons {
    Y, X, A, B, LEFT_BUMPER, RIGHT_BUMPER, BACK,
    START, DPAD_UP, DPAD_DOWN, DPAD_LEFT, DPAD_RIGHT,
    LEFT_STICK_BUTTON, RIGHT_STICK_BUTTON,
    LEFT_TRIGGER, RIGHT_TRIGGER, CIRCLE, CROSS, GUIDE, OPTIONS, PS,
    SHARE, SQUARE, TOUCHPAD, TRIANGLE
}
